import Hero from "./components/Hero";
import Generator from "./components/Generator";
import Workout from "./components/Workout";
import { useState } from "react";
import { generateWorkout } from "./utils/functions";

function App() {
  const [workoutGen, setWorkoutGen] = useState(null); // the workout generated by the function
  const [workout, setWorkout] = useState("individual"); // the workout selected in the app
  const [muscles, setMuscles] = useState([]);
  const [goals, setGoals] = useState("strength_power");

  function updateWorkoutGen() {
    if (muscles.length < 1) {
      return;
    }
    let newWorkout = generateWorkout({ workout, muscles, goals });
    console.log(newWorkout);
    setWorkoutGen(newWorkout);

    window.location.href = "#workout";
  }

  return (
    <main className="flex min-h-screen flex-col bg-gradient-to-r from-orange-500 to-orange-50 text-sm font-medium text-black sm:text-base">
      <Hero />
      <Generator
        workout={workout}
        setWorkout={setWorkout}
        muscles={muscles}
        setMuscles={setMuscles}
        goals={goals}
        setGoals={setGoals}
        updateWorkoutGen={updateWorkoutGen}
      />
      {workoutGen && <Workout workoutGen={workoutGen} />}
    </main>
  );
}

export default App;
